cards/urls.py
from django.urls import path
from cards import views

app_name = 'card'

urlpatterns = [
    path('', views.CardsListView.as_view(), name='list'),
    path('<slug:slug>/', views.CardDetailView.as_view(), name='detail'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),  # django-allauth

    # local
    path('users/', include('users.urls', namespace='users')),
    path('card/', include('cards.urls', namespace='card')),
    path('lessons/', include('lesson.urls', namespace='lesson')),
    path('courses/', include('courses.urls', namespace='course')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson/urls.py
from django.urls import path
from lesson import views

app_name = 'lesson'

urlpatterns = [
    path('', views.index, name='list'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/<int:pk>/', views.LessonCreateView.as_view(), name='create')

]

templates/html.html

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" 
    crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Главная</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Записан</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'card:list' %}">Слова</a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
              <a class="nav-link active" aria-current="page" href="{% url 'users:detail' pk=user.pk %}">Пользователь</a>
            {% endif %}
          </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Обучение
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'lesson:list' %}">Урок</a></li>
            <li><a class="dropdown-item" href="{% url 'course:list' %}">Все курсы</a></li>
            <li><a class="dropdown-item" href="#">Свои курсы</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'course:create' %}">Создать курс</a></li>
          </ul>
        </li>
       
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>     
<br>
{% block content %}
{% endblock %}
   


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>  
</body>
</html>